version: "3.3"
services:
    mcs-local-dev:
        image: node:12
        ports:
            - "41960:8080"
            - "9229:9229"
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run dev"
